### ISSUE TITLE
[BUG - Release] Fatal Error: bad conversion

### ISSUE THREAD

**Issue by StreetCaptainOfPresidents** [UE4SS-RE/RE-UE4SS#365]
**Branch or Release**
Release 2.5.1

**Game and Engine Version**
Palworld - 0.1.4.1
Unreal Engine 5

**Describe the bug**
When attempting to launch the game, the console gives the error 'Fatal Error: bad conversion'

**Mods directory**
[Mods.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14204514/Mods.zip)

**To Reproduce**
1. Install UE4SS
2. Launch Game
3. See error

**Expected behavior**
I expect the game to launch.

**Screenshots and UE4SS Log**
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14204527/UE4SS.log)

**Desktop (please complete the following information):**
Windows 11

**Additional context**
Installed using https://github.com/NattKh/PalWorld-Tools/
Another user had this issue and was directed to make a ticket here, which I could not find

**Comment by Buckminsterfullerene02** [comment]
I'm slightly confused, why is this tool using an outdated version of UE4SS? 2.5.1 is two versions out of date. Palworld is confirmed to work with either 2.5.2 or 3.0.0 (ideally 3.0.0 should be used). @NattKh care to explain?

Either way, you should try to use the latest release of UE4SS. Remember to delete the old xinput1_3.dll when you drop in the new files. https://github.com/UE4SS-RE/RE-UE4SS/releases

**Comment by UE4SS** [comment]
Unrelated but the mods included with that tool are fairly badly coded.
They have multiple `NotifyOnNewObject` calls for the same class, there's no reason to do this, each class should only have one call to `NotifyOnNewObject` per mod and all the setters can be done in the same one.

I wonder if a lot of mods do this kind of thing ? Because each call to `NotifyOnNewObject` will add one Lua function that needs to be executed every time that particular object is constructed by UE, which also means crossing the Lua/native boundary.
If a lot of mods make this mistake, you might end up with lag and longer load times.

**Comment by Buckminsterfullerene02** [comment]
> Unrelated but the mods included with that tool are fairly badly coded. They have multiple `NotifyOnNewObject` calls for the same class, there's no reason to do this, each class should only have one call to `NotifyOnNewObject` per mod and all the setters can be done in the same one.
> 
> I wonder if a lot of mods do this kind of thing ? Because each call to `NotifyOnNewObject` will add one Lua function that needs to be executed every time that particular object is constructed by UE, which also means crossing the Lua/native boundary. If a lot of mods make this mistake, you might end up with lag and longer load times.

I did a little digging and... yeah. Seems like most mods do this lol. Especially the really really big ones with hundreds of thousands of downloads. I don't know who set this "standard" of having one setter per notify on new object, but it's absolutely terrible, because everyone's following suite!

**Comment by NattKh** [comment]
Yeah it's not a standard, it was a basic kit that was made on day 1
released of the game. As an easy way to get people involved into the
modding scene. It was always meant to be a starting point, that is why
there's instructions to modify and turn off mods. At this point of the
modding scene with being able to make your own .pak in unreal engine 5.
Sideloading is a much better method. I don't recommend doing it via lua.
Again I spent 1 day on this when it was released. I have not gotten around
to playing with pal world since as I have been busy with my job.

**Comment by Buckminsterfullerene02** [comment]
Ah, that's fair enough, though still not sure why you chose 2.5.1 when 2.5.2 was out months ago. Sadly, there is 50+ stars on your repo so I think a lot of people still use it. I recommend that you update the readme to explain the temporary fix for your tool (download latest release) until you have time to fix it properly.

**Comment by NattKh** [comment]
My tool is just a downloader and unpacker for my setup. Basically you can
do the same thing by downloading the new UE4SS version and unpacking it to
your client customizing the config file to your liking and starting the
game.  I can update the source code to automatically get the newest UE4SS
version Everytime however I didn't want to be responsible for anything
breaking or changing between new version of UE4SS. So I will leave it as
is for now until I get the chance to see where everything is at. I'll
update the repo front page with the info.

**Comment by NattKh** [comment]
#OUTDATED- PalWorlds Mod Patcher - WARNING THE Tool is just a downloader
for UE4SS and an unpacker for my Lua Mod setup. YOU CAN ALWAYS DO THIS
MANUALLY! Please use this flow instead.
https://github.com/localcc/PalworldModdingKit I do not have the time to
update the repo/build it every time UE4SS releases a new version because it
would require me to test it to make sure it all still works. So I'm leaving
this up just as a show-case in how you make a downloader and unzipper :)
This is meant to be a Starter Pack, a basic organized setup for those who
want to start tinkering
done good luck yall

**Comment by UE4SS** [comment]
I believe this pull request was erroneously closed because the underlying problem wasn't actually fixed at the time that this issue was closed.
The problem has now been fixed and the fix is waiting to be merged so I'm not gonna bother reopening this problem.
It was fixed by #398
