### ISSUE TITLE
[ISSUE - Release] Actor for mod 'ModName' is not valid

### ISSUE THREAD

**Issue by EAZENLEE** [UE4SS-RE/RE-UE4SS#399]
**Branch or Release**
v3.0.0

**Game and Engine Version**
onlyclimb, steam, 5.2

**Describe the bug**
When running the game, it is still correct to see these in the console
> [08:51:11] m_shared_functions: 0x7ff9fea402a0
> [08:51:11] Enabling custom events
> [08:51:11] Starting mods (from mods.txt load order)...
> [08:51:11] Mod 'ActorDumperMod' disabled in mods.txt.
> [08:51:11] Starting Lua mod 'ConsoleCommandsMod'
> [08:51:11] Starting Lua mod 'ConsoleEnablerMod'
> [08:51:11] [Lua] ConsoleClass, GameViewport, or ViewportConsole is invalid
> [08:51:11] Mod 'SplitScreenMod' disabled in mods.txt.
> [08:51:11] Mod 'LineTraceMod' disabled in mods.txt.
> [08:51:11] Starting Lua mod 'BPModLoaderMod'
> [08:51:11] [Lua] Mods/BPModLoaderMod/load_order.txt not present or no matching mods, loading all BP mods in random order.
> [08:51:11] [Lua] ccmod == table: 0000022435892720
> [08:51:11] [Lua]     AssetNameAsFName == FNameUserdata: 0000022406AB89A8
> [08:51:11] [Lua]     AssetPath == /Game/Mods/ccmod/ModActor
> [08:51:11] [Lua]     Name == ModName
> [08:51:11] [Lua]     AssetName == ModActor_C
> [08:51:11] Starting Lua mod 'BPML_GenericFunctions'
> [08:51:11] Mod 'jsbLuaProfilerMod' disabled in mods.txt.
> [08:51:11] Starting Lua mod 'Keybinds'
> [08:51:11] Starting mods (from enabled.txt, no defined load order)...
> [08:51:11] Event loop start
> [08:51:12] [Lua] [ConsoleEnabler] ConsoleKey[1]: F10
> [08:51:12] [Lua] [ConsoleEnabler] ConsoleKey[2]: ?
> [08:51:12] [Lua] Loading mod: ModName
> [Lua] Loading mod: ccmod
 
After a few seconds, this appeared, indicating that the mod would not work. After starting the game and testing, it was indeed true that the mod did not work.
> [Lua] Actor for mod 'ModName' is not valid.

I used "ModName" instead of my mod name here and above.

**Mods directory**
[ccmod.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14328843/ccmod.zip)

**To Reproduce**
1. Launch game
2. See error in log

**Expected behavior**
If no accidents occur, a prompt starting with "Actor: ModActor_C" will appear instead of "Actor for mod 'ModName' is not valid"

**Screenshots and UE4SS Log**
![20240219171007](https://github.com/UE4SS-RE/RE-UE4SS/assets/13599438/a60eb0ea-fa60-4be4-9e1a-8d9770dedd6c)
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14328933/UE4SS.log)

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
I have also tried the experimental version of UE4SS 2.5.2 and uninstalled the game and reinstalled it, but this error still persists.

**Comment by UE4SS** [comment]
This most likely means that you've installed a non-UE4SS pak mod in `/Content/Paks/LogicMods`.

**Comment by EAZENLEE** [comment]
> This most likely means that you've installed a non-UE4SS pak mod in `/Content/Paks/LogicMods`.


I put a mod I made in LogicMods
The path of ModActor in PAK is Mods/ccmods/ModActor
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/13599438/3c9cda3c-dfd0-4504-bcf9-a1329c9a4bee)
So it's a UE4SS pak mod right?

**Comment by UE4SS** [comment]
> > This most likely means that you've installed a non-UE4SS pak mod in `/Content/Paks/LogicMods`.
> 
> I put a mod I made in LogicMods The path of ModActor in PAK is Mods/ccmods/ModActor
 So it's a UE4SS pak mod right?

Yes.

Verify that it's set up like shown in this guide: https://pwmodding.wiki/docs/creating-blueprint-mods/mod-setup-1
Ignore the fact that it's for Palworld, the ModActor set up is the same for all games, although I can't remember if the uproject name is important.

I think you also need to change some project settings in the UE editor and assign your actor to a chunk: https://pwmodding.wiki/docs/palworld-modding-kit/congratulations
If your game uses iostore (.ucas & .utoc files alongside .pak files) then you also need to tick "Use Io Store" which is in the same location as the second screenshot in the link above and you'll need to rename and copy those alongside your pak file.

**Comment by EAZENLEE** [comment]
> > > This most likely means that you've installed a non-UE4SS pak mod in `/Content/Paks/LogicMods`.
> > 
> > 
> > I put a mod I made in LogicMods The path of ModActor in PAK is Mods/ccmods/ModActor
> > So it's a UE4SS pak mod right?
> 
> Yes.
> 
> Verify that it's set up like shown in this guide: https://pwmodding.wiki/docs/creating-blueprint-mods/mod-setup-1 Ignore the fact that it's for Palworld, the ModActor set up is the same for all games, although I can't remember if the uproject name is important.
> 
> I think you also need to change some project settings in the UE editor and assign your actor to a chunk: https://pwmodding.wiki/docs/palworld-modding-kit/congratulations If your game uses iostore (.ucas & .utoc files alongside .pak files) then you also need to tick "Use Io Store" which is in the same location as the second screenshot in the link above and you'll need to rename and copy those alongside your pak file.

I have always done it like this guide, and I have checked these settings and have not found anything wrong.
So, many mods I made before have never had problems, but this time I did not make any changes to the UE editor settings, and it is the same pak packaging steps, but this time I encountered such problems

**Comment by Buckminsterfullerene02** [comment]
Fixed in latest experimental version (BPModLoader issue in ue5.2+)

**Comment by miek801** [comment]
> > > > This most likely means that you've installed a non-UE4SS pak mod in `/Content/Paks/LogicMods`.
> > > 
> > > 
> > > I put a mod I made in LogicMods The path of ModActor in PAK is Mods/ccmods/ModActor
> > > So it's a UE4SS pak mod right?
> > 
> > 
> > Yes.
> > Verify that it's set up like shown in this guide: https://pwmodding.wiki/docs/creating-blueprint-mods/mod-setup-1 Ignore the fact that it's for Palworld, the ModActor set up is the same for all games, although I can't remember if the uproject name is important.
> > I think you also need to change some project settings in the UE editor and assign your actor to a chunk: https://pwmodding.wiki/docs/palworld-modding-kit/congratulations If your game uses iostore (.ucas & .utoc files alongside .pak files) then you also need to tick "Use Io Store" which is in the same location as the second screenshot in the link above and you'll need to rename and copy those alongside your pak file.
> 
> I have always done it like this guide, and I have checked these settings and have not found anything wrong. So, many mods I made before have never had problems, but this time I did not make any changes to the UE editor settings, and it is the same pak packaging steps, but this time I encountered such problems

The two horror games GraveyardShift and Panicore come with .ucas and .utoc files as well as .pak files. I renamed them all and put them into LogicMods as you said. However, when I run the game, my blueprint mod is still not enabled. Is it because these two games don't support it?
